services:
  database:
    image: postgres:15
    container_name: weather_link_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: wl_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs-app:
    build: .
    image: hoyaa/weather-link-app:latest
    container_name: weather_link_app
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000"
    env_file:
      - .env
    command: sh -c "npm run migration:run && npm run start:prod"

  nginx:
    image: nginx:latest
    container_name: weather_link_nginx
    ports:
      - "80:80"
      - "443:443" #HTTPS 필요시 추가
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nestjs-app
volumes:
  postgres_data: