services:
  database:
    image: postgres:15
    container_name: weather_link_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: wl_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1.0'
        reservations:
          memory: 512m
          cpus: '0.5'

  nestjs-app:
    image: hoyaa/weather_link:latest
    container_name: weather_link_app
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - .env
    # command: sh -c "npm run migration:run && npm run start:prod"  #더이상 마이그레이션이 필요없을때
    command: sh -c "npm run start:prod"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.5'
        reservations:
          memory: 1g
          cpus: '0.75'

  nginx:
    image: nginx:latest
    container_name: weather_link_nginx
    ports:
      - "80:80"
      - "443:443" #HTTPS 필요시 추가
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot  # 이 줄 추가!
      - ./certbot/conf:/etc/letsencrypt  # HTTPS 적용 후 인증서 사용 시 필요
    depends_on:
      - nestjs-app
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '0.5'
        reservations:
          memory: 256m
          cpus: '0.25'

  certbot: #ssl인증서관련
    image: certbot/certbot
    container_name: weather_link_certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: '0.25'
        reservations:
          memory: 128m
          cpus: '0.1'

volumes:
  postgres_data:
